name: AWS-Infrastructure
on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"
  AWS_BUCKET: "mers.projects.bbdgrad.com"

permissions:
  id-token: write
  contents: read

jobs:
  ConfigureAwsAndTerraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Check out terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  DeployFrontend:
    runs-on: ubuntu-latest
    needs: ConfigureAwsAndTerraform
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm audit fix
      - run: npm run build
      
      - name: Deploy
        if: success()
        run: aws s3 sync "${{ github.workspace }}/frontend/dist/my_first_angular" ${{ env.AWS_BUCKET }}
